language: ruby
cache: bundler
script: bundle exec rspec
sudo: false

gemfile:
  - gemfiles/rack_1.5.gemfile
  - gemfiles/rack_1.6.gemfile
  - gemfiles/rack_2.0.gemfile
  - gemfiles/rack_2.1.gemfile
  - gemfiles/rack_2.2.gemfile

rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.8
  - 2.6.5
  - 2.7.0

before_install:
  - gem install bundler -v 1.17.2
